name: Print file
on: push

jobs: 
  print: 
    runs-on: ubuntu-latest
    steps: 
      - name: Chekout repository
        uses: actions/checkout@v3
    
      - name: Print hello world on terminal
        run: echo '$(hello_world.txt)'
